krzema12/snakeyaml-engine-kmp

src/test/java/org/snakeyaml/engine/issues/issue149/GlobalDirectivesTest.java, src/test/java/org/snakeyaml/engine/issues/issue39/EmitCommentAndSpacesTest.java, src/test/java/org/snakeyaml/engine/issues/issue512/ListWithCommentTest.java, src/test/java/org/snakeyaml/engine/usecases/env/EnvVariableTest.java, src/test/java/org/snakeyaml/engine/usecases/indentation/IndentWithIndicatorTest.java, src/test/java/org/snakeyaml/engine/usecases/inherited/InheritedImportTest.java, src/test/java/org/snakeyaml/engine/usecases/inherited/InheritedMarkTest.java, src/test/java/org/snakeyaml/engine/usecases/recursive/RecursiveSetTest.java, src/test/java/org/snakeyaml/engine/usecases/references/DumpAnchorTest.java, src/test/java/org/snakeyaml/engine/v2/api/LoadMappingTest.java, src/test/java/org/snakeyaml/engine/v2/api/LoadSequenceTest.java, src/test/java/org/snakeyaml/engine/v2/constructor/StandardConstructorTest.java, src/test/java/org/snakeyaml/engine/v2/utils/TestUtils.java
Depends on
* No dependencies!
Minor QOL improvement in the Test DSL. Annotating the file paths with `@Language("file-reference")` means the files can be opened in IntelliJ by ctrl+clicking the file path.
Missing files are highlighted.
For this to work, 
* all paths need to be absolute from the root resources (all paths were already the full file path, I just needed to add the base `/`)
* use `java.getResouce()` instead of `classLoader.getResource()`.
This is a test-only change and does not have any impact on the library.
=> add `@Language("file-reference")` for extra clickability in test utils

src/test/java/org/snakeyaml/engine/v2/api/DumpTest.java
I kept seeing a `./target/` dir pop-up, which was confusing because we're using Gradle now there's no more target dir. 
I figured out the cause was this test creating a temporary file. I updated it to use the temp-file util instead.
=> use temp file for test

.github/workflows/git-branch-publish.yml, README.md, build.gradle.kts, buildSrc/src/main/kotlin/buildsrc/conventions/git-branch-publish.gradle.kts
Adds a GH Workflow and Gradle config that will publish SnakeYAML to the (orphaned) [artifacts](https://github.com/krzema12/snakeyaml-engine-kmp/tree/artifacts) branch.
@krzema12 can you do the following:
=> setup git-branch-publish util

.github/workflows/build.main.kts, .github/workflows/build.yaml
This will cancel in-progress workflows if a new commit is added.
Adding this is especially important now that most Kotlin targets are activated, so the tests take a long time to complete.
=> add concurrency & cancellation to 'build' workflow

src/commonMain/kotlin/org/snakeyaml/engine/v2/api/lowlevel/ComposeString.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/composer/Composer.kt, src/jvmMain/java/org/snakeyaml/engine/v2/api/Load.kt, src/jvmMain/java/org/snakeyaml/engine/v2/api/lowlevel/Compose.kt
convert `val singleNode` to `fun getSingleNode()` to better match SnakeYAML
https://github.com/snakeyaml/snakeyaml-engine/blob/5a35e1fe7f780d1405d5a03470f9f13d32b1638a/src/main/java/org/snakeyaml/engine/v2/composer/Composer.java#L113-L140
=> convert `val singleNode` to `fun getSingleNode()`

build.gradle.kts
To keep the version in a single place, so that Renovate bumps all kotest-related packages at once.
=> Use BOM package for kotest

src/commonMain/kotlin/org/snakeyaml/engine/internal/math.kt, src/commonMain/kotlin/org/snakeyaml/engine/internal/system.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/api/ConstructNode.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/api/LoadSettingsBuilder.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/api/lowlevel/Parse.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/common/CharConstants.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/composer/Composer.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/constructor/BaseConstructor.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/constructor/StandardConstructor.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/emitter/Emitter.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/events/CollectionStartEvent.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/events/ScalarEvent.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/exceptions/MissingEnvironmentVariableException.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/nodes/CollectionNode.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/nodes/Node.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/nodes/NodeTuple.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/parser/ParserImpl.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/scanner/ScannerImpl.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/serializer/Serializer.kt, src/commonTest/kotlin/org/snakeyaml/engine/SimpleEndToEndTest.kt, src/jsMain/kotlin/org/snakeyaml/engine/v2/api/lowlevel/Parse.kt, src/jvmMain/java/org/snakeyaml/engine/v2/api/lowlevel/Parse.kt, src/nativeMain/kotlin/org/snakeyaml/engine/v2/api/lowlevel/Parse.kt
code and docs tidying, in preparation for YAML Test Suites #59 
- remove unused `toBigDecimal` function
- avoid using `!!` to force non-null
- update Parse to have multiplatform constructor
- add/adjust docs and docs formatting
- avoid using scope functions for simple checks (scope functions tend to be more difficult to read)
- refactor environment variable fetching (improve legibility, and prepare for multiplatform testing)
- use sealed classes where possible (because the classes are not intended to be extended by external libraries)
- convert `NodeTuple` to regular class (data classes ABI is more difficult to maintain)
- re-write while-loops to avoid awkward scope functions and variable assignments
- Replace custom `StreamDataWriter` in test with existing `StringStreamDataWriter`
=> Kotlin code improvements 

build.gradle.kts, buildSrc/src/main/kotlin/buildsrc/conventions/lang/kotlin-multiplatform-js.gradle.kts, buildSrc/src/main/kotlin/buildsrc/conventions/lang/kotlin-multiplatform-native.gradle.kts, gradle.properties
- enable Gradle config cache (Kotlin 1.9 is now compatible)
- update Gradle config cache property names
- use Kotlin default hierarchy https://kotlinlang.org/docs/multiplatform-hierarchy.html#default-hierarchy-template
- fix Kotlin config deprecations
=> tidy build config after Gradle & Kotlin updates

src/jvmTest/java/org/snakeyaml/engine/usecases/references/ReferencesTest.java
I think the test is failing on CI because the test is performing worse than expected.
[Example failure](https://github.com/krzema12/snakeyaml-engine-kmp/actions/runs/7593971736/job/20685006620#step:5:284): 
```
ReferencesTest[jvm] > Parsing with aliases may take a lot of time, CPU and memory[jvm] FAILED
org.opentest4j.AssertionFailedError: Time was 11.039 seconds. ==> expected: <true> but was: <false>
at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at app//org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
at …
```
=> fix test parseManyAliasesForCollections

settings.gradle.kts
custom Kotlin/Native repos aren't needed any more - they're published to Maven Central
=> Remove custom Kotlin/Native repos

settings.gradle.kts
Reverts krzema12/snakeyaml-engine-kmp#128
Apparently the artifacts are on Maven Central, but a custom repo is still required.
=> Revert "Remove custom Kotlin/Native repos"

src/commonMain/kotlin/org/snakeyaml/engine/v2/exceptions/ComposerException.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/exceptions/ConstructorException.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/exceptions/MarkedYamlEngineException.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/exceptions/ParserException.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/exceptions/ScannerException.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/scanner/ScannerImpl.kt
Improvements for MarkedYamlEngineException, for use by Kaml in https://github.com/charleskorn/kaml/pull/507
- make 'problem' required (matches existing usages)
- make context/problems properties (they are used by Kaml)
- fix problem/context order of ScannerException in ScannerImpl
=> Tidy MarkedYamlEngineException

build.gradle.kts
This PR adds an external link to the Okio docs, meaning that in our API reference docs, the Okio types will be clickable and linked to the Okio API reference docs.
=> add external link to Okio docs

src/commonMain/kotlin/org/snakeyaml/engine/v2/emitter/Emitter.kt, src/jvmTest/java/org/snakeyaml/engine/v2/emitter/EmitterTest.java
Resolves #152.
It looks like a coding error when porting snakeyaml-engine to Kotlin. The original project contains:
https://github.com/krzema12/snakeyaml-engine-kmp/blob/04614c75c124d30c58221ab11255c5d45d913a14/src/main/java/org/snakeyaml/engine/v2/emitter/Emitter.java#L213-L216
which I'm reimplementing in this PR.
BTW, there's no unit test for this behavior in snakeyaml-engine, and ideally we'd like to add it there as well. It would have prevented this regression.
=> Fix setting width greater than the default

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/ComposeString.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/ParseString.kt, src/jvmMain/java/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Compose.kt, src/jvmMain/java/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Parse.kt
Using `Iterable {}` avoids creating an unnecessary Sequence instance
=> Replace `.asSequence().asIterable()` with `Iterable {}`

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/ScannerImpl.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/test_suite/SuiteUtils.kt, src/jvmTest/java/org/snakeyaml/engine/usecases/external_test_suite/SuiteUtils.java
- Always permit spaces and tabs when scanning plain spaces, not just the initial whitespace.
- Add note regarding empty-key test-suite cases
=> Fix scanning for tabs in plain-spaces

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/constructor/BaseConstructor.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/constructor/StandardConstructor.kt
- Resolve TODO, and improve defensiveness (avoid a mutable map for tagConstructors)
- Add error message with details if NULL constructor is missing
- tidy KDoc
=> Refactor StandardConstructor

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/common/CharConstants.kt
Simplify `CharConstants.escapeChar()` for 1. readability, and 2. performance (currently it iterates multiple times through `ESCAPE_REPLACEMENTS` - which can be avoided).
=> Simplify `CharConstants.escapeChar()`

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Parse.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/ParseCommon.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/ParseString.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/test_suite/SuiteUtils.kt, src/jsMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Parse.kt, src/jvmMain/java/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Parse.kt, src/jvmTest/java/org/snakeyaml/engine/issues/issue149/GlobalDirectivesTest.java, src/jvmTest/java/org/snakeyaml/engine/usecases/external_test_suite/ParseSuiteTest.java, src/jvmTest/java/org/snakeyaml/engine/usecases/external_test_suite/SuiteUtils.java, src/jvmTest/java/org/snakeyaml/engine/v2/api/lowlevel/ParseEmitTest.java, src/jvmTest/java/org/snakeyaml/engine/v2/api/lowlevel/ParseTest.java, src/nativeMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Parse.kt
- Create ParseCommon, for shared commonMain Parsing code
- Rename functions, so they're overloaded based on the arg type
- Deprecate unnecessary ParseString
- De-duplicate/tidy KDoc
=> Refactor Parse

.idea/codeStyles/Project.xml
IntelliJ keeps removing the `<editorconfig>` section - I think it's not necessary any more.
Follow-up to #165
=> remove editorconfig from Project.xml codestyle

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Compose.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/ComposeCommon.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/ComposeString.kt, src/jsMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Compose.kt, src/jvmMain/java/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Compose.kt, src/jvmTest/java/org/snakeyaml/engine/usecases/env/EnvTagTest.java, src/jvmTest/java/org/snakeyaml/engine/usecases/external_test_suite/ComposeSuiteTest.java, src/jvmTest/java/org/snakeyaml/engine/usecases/external_test_suite/EmitSuiteTest.java, src/jvmTest/java/org/snakeyaml/engine/usecases/references/DumpAnchorTest.java, src/jvmTest/java/org/snakeyaml/engine/v2/api/OptionalMarksTest.java, src/jvmTest/java/org/snakeyaml/engine/v2/api/lowlevel/ComposeTest.java, src/jvmTest/java/org/snakeyaml/engine/v2/common/SpecVersionTest.java, src/jvmTest/java/org/snakeyaml/engine/v2/composer/ComposerTest.java, src/jvmTest/java/org/snakeyaml/engine/v2/constructor/StandardConstructorTest.java, src/nativeMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/lowlevel/Compose.kt
- Create ComposeCommon, for shared commonMain composing code
- Rename functions, so they're overloaded based on the arg type
- Deprecate unnecessary ComposeString
- De-duplicate/tidy KDoc
=> Refactor Compose

src/jvmMain/java/it/krzeminski/snakeyaml/engine/kmp/api/YamlOutputStreamWriter.kt, src/jvmTest/java/org/snakeyaml/engine/v2/api/DumpTest.java
- Update KDoc
- IOException shouldn't be nullable
- provide default implementation for `processIOException()`
- change class from `abstract` to `open`, so it's easier to use
=> refactor YamlOutputStreamWriter

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/ScannerImpl.kt
There's no need to skip BOMs in ScannerImpl. ScannerImpl gets the characters from StreamReader, which skips BOMs. Skipping them again here is redundant.
=> Remove BOM skip in ScannerImpl

src/jvmTest/java/org/snakeyaml/engine/issues/issue51/LoadSettingsBufferSizeTest.java
cherry picked from upstream commit [ef7ebe9c06e963e13f4ab465f300a0dd6f0940c9](https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/ef7ebe9c06e963e13f4ab465f300a0dd6f0940c9)
SnakeKMP isn't affected by [the issue](https://bitbucket.org/snakeyaml/snakeyaml-engine/issues/51/find-a-way-to-dump-as-json), but more tests don't hurt. I'm planning to refactor StreamReader, so this test will be useful.
=> Cherrypick test from upstream: Fix issue 51 - use the full buffer

src/jvmTest/java/it/krzeminski/snakeyaml/engine/kmp/scanner/StreamReaderTest.kt
There are currently no direct tests for StreamReader. If a bug is introduced into StreamReader, it can be hard to track down the root cause, because unrelated tests will fail. Adding some simple tests helps verify that StreamReader is working as expected.
=> Add StreamReader tests

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/exceptions/Mark.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/internal/utils/AppendableExtensions.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/internal/utils/CharSequenceExtensions.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/internal/utils/Character.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/StreamReader.kt, src/jvmTest/java/org/snakeyaml/engine/usecases/inherited/CanonicalScanner.java, src/jvmTest/java/org/snakeyaml/engine/usecases/inherited/InheritedMarkTest.java, src/jvmTest/java/org/snakeyaml/engine/v2/events/EventTest.java, src/jvmTest/java/org/snakeyaml/engine/v2/exceptions/MarkTest.java
- Change codepoint buffer from mutable `IntArray` to read-only `List<Int>`
- Deprecate alternate constructors. They were only used in tests, and the 'real' constructor wasn't tested.
- update kdoc
- trim Mark.name in `toString()` (the yaml-test-suite tests end with newlines, which lead to weird output messages)
- refactor `createSnippet()` to be more Kotlin-ey
- add more Character & Codepoint utils
=> Refactor Mark

src/jvmTest/java/org/snakeyaml/engine/usecases/inherited/CanonicalScanner.java, src/jvmTest/java/org/snakeyaml/engine/usecases/inherited/InheritedCanonicalTest.java
Fix minor warnings, including but not limited to:
- Unnecessary boxing 
- 'null' is returned by the method declared as `@NotNull`
- Not annotated method overrides method annotated with `@NotNull`
=> Fix warnings in CanonicalScanner and InheritedCanonicalTest

.github/workflows/build.main.kts
The new URL is a part of stabilizing the feature of action bindings served as Maven artifacts.
For details, see the announcement:
https://kotlinlang.slack.com/archives/C02UUATR7RC/p1718314294799469
=> Update URL for action bindings

api/snakeyaml-engine-kmp.api, build.gradle.kts
It will let us get more confidence that no API changes (wrt. signatures) are introduced whenever we e.g. refactor stuff, and help us review API changes if we make them.
=> Add JVM API dump

snake-kmp-benchmarks/build.gradle.kts, snake-kmp-benchmarks/src/jvmMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/benchmark/SnakeyamlEngineJvmLoadingTimeBenchmark.kt
This way we should have a reference point to the implementation where SnakeYAML Engine KMP was forked from.
=> Add performance comparison to snakeyaml-engine

.github/workflows/benchmark.main.kts, .github/workflows/benchmark.yaml
Use [github-workflows-kt](https://github.com/typesafegithub/github-workflows-kt) to implement the workflow in Kotlin, increasing maintainability and readability.
Note: proper, type-safe matrix strategy support is yet to be implemented, it's tracked in https://github.com/typesafegithub/github-workflows-kt/issues/368.
1. Compared what's logged in the "Store benchmark result" step as "Data", and there are no differences.
* version from `main` branch: https://github.com/krzema12/snakeyaml-engine-kmp/actions/runs/10187305280/job/28181268567
* version from this branch: https://github.com/krzema12/snakeyaml-engine-kmp/actions/runs/10244555647/job/28338076917?pr=221
2. Compared with https://www.yamldiff.com/. Most important differences:
* the new version has a consistency check which is required …
=> Use Kotlin DSL for benchmark workflow

.github/workflows/build.main.kts, .github/workflows/build.yaml, .github/workflows/release.main.kts, .github/workflows/release.yaml, buildSrc/src/main/kotlin/buildsrc/conventions/publishing.gradle.kts
Part of #94
The workflow uses [nexus-actions](https://github.com/nexus-actions) to manage the staging repository. The publication was updated to use the new URL for deployment when a staging repository ID is available.
The following secrets should be added to the project:
- SONATYPE_USERNAME
- SONATYPE_PASSWORD
- SONATYPE_STAGING_PROFILE_ID (can be obtained using this link: https://oss.sonatype.org/#stagingProfiles;$staginProfileId)
- SIGNING_KEY_ID
- SIGNING_KEY
- SIGNING_PASSWORD
@aSemy @krzema12 Could you please take a look at the changes when you have time? Unfortunately, I don't have an OSS account (only OSS1) and cannot test the workflow by myself. But if you have any issues when trying to publish a new release I will be happy to help
=> Add GitHub workflow to publish a release

.github/workflows/build.main.kts, .github/workflows/build.yaml
Now that we have a workflow that runs only on demand, and not in every PR or on the `main` branch, it's beneficial to have these extra checks.
BTW, I noticed this piece is useful in almost every project, and I'm planning to release some kind of util (a GitHub action?) that would encapsulate this logic. It's tracked in https://github.com/typesafegithub/github-workflows-kt/issues/213
Examples of using this approach in other repos:
* https://github.com/typesafegithub/github-workflows-kt/blob/0e91c566849a5883b39021a5ecbc18d25b006c1b/.github/workflows/build.main.kts#L95
* https://github.com/typesafegithub/github-actions-typing-catalog/blob/667df7ec3fc639d19e278fc5956a9f753b26bb90/.github/workflows/test.main.kts#L14
=> Check consistency and compilability of all GitHub workflows

.github/workflows/release.main.kts, .github/workflows/release.yaml
In the test run the job to drop staging repo was not executed after publication failed. This should solve the problem.
Part of #94
=> Execute drop staging repo job in case of failure

.github/workflows/check-upstream.main.kts, .github/workflows/check-upstream.yaml
Part of #260.
Adding such simple workflow to be able to run it through the UI, and further iterate on it.
=> Add stub of workflow for checking the state of upstream project

.github/workflows/check-upstream.main.kts, .github/workflows/check-upstream.yaml, README.md
Part of #260.
Thanks to this, we can preview what commits need to be synced.
=> Link to log diff between repost in "To upstream" badge

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/events/ScalarEvent.kt
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/283.
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/2347d09845f57d416e1f19bf950640f5eb398b56
There's no point in mentioning all possible values since we have the enum, it's even bad because it duplicates the knowledge about the possible values. It can get outdated easily.
=> [Port from snakeyaml-engine] Refactor: comment changed

buildSrc/src/main/kotlin/buildsrc/conventions/lang/kotlin-multiplatform.gradle.kts
It's related to https://github.com/krzema12/snakeyaml-engine-kmp/pull/231.
The test fail on Kotlin 2.1.0 and/or Kotest 6.0, and we don't know why yet. Given that Wasm is still experimental and unstable, we want to release the library for other targets. That's why I recommend disabling the tests, and tracking the issue in https://github.com/krzema12/snakeyaml-engine-kmp/issues/320. Once the tests are skipped, we'll be able to unblock merging https://github.com/krzema12/snakeyaml-engine-kmp/pull/231 (I tested this change with the mentioned PR and CI is green).
This change is made in a separate PR for visibility.
=> Temporarily disable Wasm tests

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/LoadSettingsBuilder.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/StreamReader.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/ReaderStringTest.kt
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/c36e42f972c53d851a91e2a2c6323a4c066da662
This PR actually doesn't modify the behavior because we use Okio which handles reading UTF-8 for us. We just need to port the tests and make some adjustments in the docstrings.
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/292
=> [Port from snakeyaml-engine] Allow HighSurrogate to be the last char in the data window

settings.gradle.kts
Helpful with troubleshooting failed builds, especially if they failed on a runner that one doesn't have available.
A direct motivation for it are failing tests in https://github.com/krzema12/snakeyaml-engine-kmp/pull/324. However, the issue is weird there: if I enable build scans in that PR, the tests pass. Adding the build scans in general is a good thing, so here's a separate PR.
=> Publish build scans in case of failures

buildSrc/src/main/kotlin/buildsrc/conventions/multiplatform-test-resources.gradle.kts, buildSrc/src/main/kotlin/buildsrc/tasks/ConvertCommonTestResourcesToKotlin.kt
Thanks to this fix, the accessor class is regenerated if the resources dir's content changes.
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/327.
=> Fix caching for generating test resources accessor

settings.gradle.kts, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/CommonTestResourcesAccess.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/CommonTestResourcesAccessTest.kt, src/commonTest/resources/test/resource/foo.txt
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/323
Replaces NPE with an IllegalArgumentException with a nice message.
=> Handle non-existing common test resources gracefully

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/StreamReader.kt
I noticed that we make a copy of a codepoint window when `prefix(int)` method is called. It looks redundant since the `StreamReader` should not be invoked from different threads and the resulting `String` is immutable.
I have changed the code build string without making a copy and got a significant performance increase on local benchmarks (let see how it behaves in CI)
```text
Benchmark                                                 Mode  Cnt   Score   Error  Units
LoadingTimeBenchmark.loadsOpenAiSchema                    avgt   10  15.655 ± 0.138  ms/op
SnakeyamlEngineJvmLoadingTimeBenchmark.loadsOpenAiSchema  avgt   10  13.554 ± 0.348  ms/op
```
Related to #266
=> performance: avoid making codepoints window copy on prefix call

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/StreamReader.kt
A small optimization to avoid creating an `Integer` object. Method `getOrNull` must return an object since it can return a `null` value. Using `getOrElse` will always return a primitive value. It is not much but it is something (until I figure out what to do with `StreamReader.update` method)
Related to #266
=> performance: avoid boxing when making array's copy

src/jsCommonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/internal/system.js.kt, src/jsMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/internal/process.kt, src/jsMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/internal/system.js.kt, src/wasmJsMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/internal/system.wasm.kt
While working on https://github.com/krzema12/snakeyaml-engine-kmp/pull/332, I found out that the implementations for JS and WASM JS are missing. This PR focuses on adding them. I don't want to add these in the PR that is related solely to kotlinizing and commonizing the tests to give this fix a proper visibility in the release notes.
This change was tested within https://github.com/krzema12/snakeyaml-engine-kmp/pull/332, and the goal is to merge that PR soon after this one lands.
Note: env vars work only in a non-browser environment.
=> Fix reading env vars for JS and WASM JS (only NodeJS)

build.gradle.kts, buildSrc/src/main/kotlin/buildsrc/conventions/lang/kotlin-multiplatform.gradle.kts, gradle/kotlin-js-store/yarn.lock
Closes #320.
Related to https://kotlinlang.slack.com/archives/CDFP59223/p1736171757249559?thread_ts=1734964013.996149&cid=CDFP59223
> The problem in linkage of coroutines 1.8.0 (which was built against Kotlin/Wasm 1.9.21) with Kotlin stdlib 2.1.0.
In 2.1.0 we have some changes in our linkage process (including changes in stdlib), so I’d recommend to use new Kotlin coroutines which was built with Kotlin 2.1.0
For example the latest one with version 1.10.1
=> Re-enable WASM JS tests

src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/CommonTestResourcesAccess.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/CommonTestResourcesAccessTest.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/LoadMappingTest.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/LoadSequenceTest.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/issues/issue149/GlobalDirectivesTest.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/issues/issue39/EmitCommentAndSpacesTest.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/usecases/env/EnvVariableTest.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/usecases/indentation/IndentWithIndicatorTest.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/usecases/references/DereferenceAliasesTest.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/usecases/references/DumpAnchorTest.kt, src/jvmTest/java/it/krzeminski/snakeyaml/engine/kmp/usecases/env/EnvVariableJvmTest.kt
Thanks to this, we'll be able to use `@Language("file-reference")` to validate the paths in the IDE. Now it's impossible due to a bug in the library that provides the annotation, see https://github.com/JetBrains/java-annotations/issues/116.
This PR is a mergeable part of https://github.com/krzema12/snakeyaml-engine-kmp/pull/349.
=> Add leading slash in path to common test resources

buildSrc/src/main/kotlin/buildsrc/tasks/ConvertCommonTestResourcesToKotlin.kt
Part of https://github.com/krzema12/snakeyaml-engine-kmp/issues/354
Before this change, the build logic took all test resources, and converted them into Kotlin code that was building a map using a single expression with using nested `mapOf` function to represent the directory structure. However, when trying to move existing JVM-specific resources (there's a lot of them), one could see a failing build with:
```
exception: java.lang.RuntimeException: Error generating class file CommonTestResources.class (compiled from [/Users/piotr/repos/snakeyaml-engine-kmp/build/generated-code-for-resources/src/commonTest/kotlin/CommonTestResources.kt]): Method too large: CommonTestResources.<clinit> ()V
e
```
This change puts every call to `mapOf(...)` or `ByteString.of(...)` into a separate method, so …
=> Allow larger common test resources

src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/issues/issue53/DumpWithoutCommentsTest.kt
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/317.
Let's have this basic assertion, so that this test doesn't only rely on certain function calls not throwing exceptions.
=> Add assertion to DumpWithoutCommentsTest

src/jvmTest/java/it/krzeminski/snakeyaml/engine/kmp/internal/FSPath.kt, src/jvmTest/java/it/krzeminski/snakeyaml/engine/kmp/usecases/inherited/InheritedCanonicalTest.kt, src/jvmTest/java/it/krzeminski/snakeyaml/engine/kmp/usecases/inherited/InheritedImportUtils.kt, src/jvmTest/java/it/krzeminski/snakeyaml/engine/kmp/usecases/inherited/InheritedReaderTest.kt, src/jvmTest/java/it/krzeminski/snakeyaml/engine/kmp/usecases/inherited/InheritedTokensTest.kt
Part of https://github.com/krzema12/snakeyaml-engine-kmp/issues/269.
I'm planning to implement Okio's file system to reflect the common test resources, so this refactoring brings us closer to this idea.
=> Use Okio in inherited tests

src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/CommonTestResourcesAccess.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/CommonTestResourcesAccessTest.kt
Part of https://github.com/krzema12/snakeyaml-engine-kmp/issues/269.
It's a step towards using other common test resources. It focuses on implementing the custom Okio file system, and while we're doing it, we can reuse it for retrieving a single common test resource to avoid duplication.
=> Implement file system based on common test resources and use it in stringFromResources

karma.config.d/karma.conf.js
There is one more parameter that can help reduce the chances of getting error:
> ChromeHeadless has not captured in 60000 ms, killing.
Related to #307
=> Increase browserSocketTimeout parameter for karma tests

karma.config.d/karma.conf.js
Last time we had an error during test execution on macOS we saw that the **captureTimeout** parameter was not applied. This happened because the content of `karma.config.d/karma.conf.js` file was merged into the following block:
```js
module.exports = function(config) {
// kotlin configuration
// ...
// content from our file
}
```
As a result, it looked like this:
```js
module.exports = function(config) {
// kotlin configuration
// ...
// content from our file
module.exports = function(config) {
}
}
```
That was the reason, why our configuration changes were not applied. Let's see what happens with #307 issue after we correct the `karma.conf.js`
=> Correct how config parameters for karma are set

buildSrc/src/main/kotlin/buildsrc/conventions/multiplatform-test-resources.gradle.kts, buildSrc/src/main/kotlin/buildsrc/tasks/ConvertCommonTestResourcesToKotlin.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/CommonTestResourcesAccess.kt
The goal is to allow accessing resources not only from `commonTest/resources`, but also from an arbitrary directory known during build time. In particular, we already generate code for the YAML comprehensive test suite ([buildSrc/src/main/kotlin/buildsrc/tasks/GenerateYamlTestSuiteData.kt](https://github.com/krzema12/snakeyaml-engine-kmp/blob/main/buildSrc/src/main/kotlin/buildsrc/tasks/GenerateYamlTestSuiteData.kt)), and we can replace it with the new code generation approach being adjusted in this PR. Thanks to this change, we'll be able to expose the YAML test data as a separate Okio file system, conveniently traversable in the tests.
This PR is just a piece of refactoring allowing it. Migrating the YAML test suite to use this approach will be done in a separate PR, to make things …
=> Allow reusing common test resources code generation

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/StringStreamDataWriter.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/StringStreamDataWriterTest.kt
During debugging, it was confusing to see some contents of the buffer when pausing in the debugger before an assertion, but then seeing the assertion fail. It didn't make sense why the assertion fails - the value of the buffer was as expected.
It turned out that the debugger called `toString()`, consuming the buffer, and leaving an empty buffer when performing the assertion. The solution here is to just `peek()` the buffer in `toString()`, not consume it.
=> Fix StringStreamDataWriter.toString to not consume buffer

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts, gradle/libs.versions.toml
I see that Renovate managed to bump two packages, and for other packages, CI is failing. Not sure if it's because the artifacts are broken, or the changes need to go together. To solve it, let's make Renovate bump versions of all kotest-related packages at once, for the sake of consistency.
This change downgrades some kotest-related libraries to 6.0.0.M1.
=> Synchronize kotest version to 6.0.0.M1 via version catalog

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/resolver/CoreScalarResolver.kt
Found when converting the corresponding test to KMP: https://github.com/krzema12/snakeyaml-engine-kmp/pull/397
What helped me here is this tool that renders the regex as a graph: https://www.debuggex.com/
Before the fix - I noticed that `^` and `$` are attached to the groups nearest to them:
After the fix - creating a new group that contains the rest fixes the problem:
=> Fix CoreScalarResolver.INT regex to work with JS

build.gradle.kts, gradle/libs.versions.toml
Looks like we don't use it anywhere, and kotest 6.0.0.M2 doesn't have this artifact (see https://github.com/kotest/kotest/pull/4590).
This change is needed to update to 6.0.0.M2: https://github.com/krzema12/snakeyaml-engine-kmp/pull/400.
=> Remove dependency on kotest-framework-api

buildSrc/src/main/kotlin/buildsrc/conventions/base.gradle.kts
Part of https://github.com/krzema12/snakeyaml-engine-kmp/issues/405.
Judging by the comment, this piece of config is probably for the sake of keeping the directory tree clean, and not to implement certain behavior. This piece also breaks publishing of KLibs in Kotlin 2.1.0, because of reasons described in https://youtrack.jetbrains.com/issue/KT-74871/KN-NoSuchFileException-default-targets-linuxx64-kotlin-with-snakeyaml-engine-kmp-3.1.0#focus=Comments-27-11510364.0-0.
=> Fix publishing for native targets

build.gradle.kts, buildSrc/build.gradle.kts, gradle/libs.versions.toml, snake-kmp-benchmarks/build.gradle.kts
For the sake of easier management of versions, and to make automatic version bumps easier.
=> Move all dependencies to Gradle version catalog

snake-kmp-benchmarks/build.gradle.kts
Thanks to https://github.com/Kotlin/kotlinx-benchmark/pull/292, we don't have to specify this transitive dependency anymore.
=> Remove explicit dependency on urlencoder-lib in benchmark project

buildSrc/src/main/kotlin/buildsrc/conventions/lang/kotlin-multiplatform.gradle.kts
Let's use the JDK that is available on the host. Thanks to requiring specific JDK for Kotlin and Java compilation, Gradle will fail if no sufficiently new JDK is available.
=> Remove usage of Gradle toolchain

.junie/guidelines.md
Part of https://github.com/krzema12/snakeyaml-engine-kmp/issues/269.
See https://www.jetbrains.com/help/junie/customize-guidelines.html. With these guidelines, Junie managed to prepare https://github.com/krzema12/snakeyaml-engine-kmp/pull/500, I just had to manually work on replacing Java-specific stream API.
=> Add guidelines for Junie for porting tests to Kotlin

src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/issues/issue47/SetWidthTest.kt
Fixes https://github.com/krzema12/snakeyaml-engine-kmp/issues/506.
Ports multiple changes since individual commits make changes that make the tests fail, only the last commit makes the tests pass:
* https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/7eea790d14c986276f0095dd87694d5510cb34fd
* https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/061a977e9830bbd300e3a3c0cddf553a2ff4275c
* https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/9dfb6b6a1a45f4802f4ae3de5b22353cdc101724
* https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/e55f1a6957d5f422f62dd61260ca68a2ac9a01a8
=> [Port from snakeyaml-engine] Add tests for dividing strings with spaces

buildSrc/src/main/kotlin/buildsrc/conventions/yaml-testing.gradle.kts, gradle/wrapper/gradle-wrapper.properties
This PR reverts https://github.com/krzema12/snakeyaml-engine-kmp/pull/484.
It's needed because kotest 6.0.0 doesn't support Gradle 9 yet (https://github.com/kotest/kotest/issues/5019), and it's better to use kotest 6.0.0 to be able to use Kotlin 2.2.0+, and wait for Gradle 9.
=> Revert updating to Gradle 9

.github/workflows/build.main.kts, .github/workflows/build.yaml, buildSrc/src/main/kotlin/buildsrc/conventions/lang/kotlin-multiplatform.gradle.kts
The immediate reason for this change is not being able to update to kotest 6.0.0 and Kotlin 2.2.0.
See e.g. https://github.com/krzema12/snakeyaml-engine-kmp/actions/runs/17149519010/job/48656766305:
```
java.lang.IllegalStateException: Errors occurred during launch of browser for testing.
> Task :jsBrowserTest
- ChromeHeadless
Please make sure that you have installed browsers.
Or change it via
browser {
testTask {
useKarma {
useFirefox()
useChrome()
useSafari()
}
}
}
```
It's weird because there's Chrome in the runner image: https://github.com/actions/runner-images/blob/9943ce2a33e95ba38691c0b26d5079a3216718e1/images/macos/macos-15-arm64-Readme.md?plain=1#L92. In general, MacOS workers are pretty weak, and make the builds longer. This change leads to not running browser tests on MacOS, …
=> On MacOS in CI, just run tests for MacOS/iOS targets

src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/test_suite/SuiteUtils.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/test_suite/TestSuiteTests.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/test_suite/YamlTestData.kt
Part of #561.
This change is inspired by https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/190cd4c18930bef571771e9c98371d224ddef0c3, but instead of comments we have strings that are validated against the test cases' labels, and there's no info about other parsers impacted by a given deviation.
=> Annotate failing YAML test suite cases with labels

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/ScannerImpl.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/issues/issue69/TabInDoubleQuoteTest.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/test_suite/Deviations.kt
Fixes https://github.com/krzema12/snakeyaml-engine-kmp/issues/560.
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/5656f99119c07ed5be6bbf42e7a6f4eadb67a86d.
=> [Port from snakeyaml-engine] Parse escaped TAB in double-quoted scalar
