krzema12/snakeyaml-engine-kmp

src/main/java/org/snakeyaml/engine/v2/emitter/Emitter.kt, src/main/java/org/snakeyaml/engine/v2/emitter/ScalarAnalysis.kt, src/main/java/org/snakeyaml/engine/v2/events/DocumentStartEvent.kt, src/main/java/org/snakeyaml/engine/v2/events/Event.kt, src/main/java/org/snakeyaml/engine/v2/events/NodeEvent.kt, src/main/java/org/snakeyaml/engine/v2/events/ScalarEvent.kt, src/main/java/org/snakeyaml/engine/v2/nodes/AnchorNode.kt, src/main/java/org/snakeyaml/engine/v2/nodes/Node.kt, src/main/java/org/snakeyaml/engine/v2/parser/VersionTagsTuple.kt, src/main/java/org/snakeyaml/engine/v2/scanner/SimpleKey.kt, src/main/java/org/snakeyaml/engine/v2/scanner/StreamReader.kt, src/main/java/org/snakeyaml/engine/v2/tokens/CommentToken.kt, src/main/java/org/snakeyaml/engine/v2/tokens/DirectiveToken.kt, src/main/java/org/snakeyaml/engine/v2/tokens/Token.kt
* Remove utility functions used during the j2k conversion
* Renamed some properties to match Java bean naming conventions
* removed an unrelated TODO
=> Remove j2k util functions

.github/workflows/build.main.kts, .github/workflows/build.yaml, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/buildsrc/conventions/lang/kotlin-multiplatform-native.gradle.kts, src/nativeMain/kotlin/org/snakeyaml/engine/internal/math.native.kt, src/nativeMain/kotlin/org/snakeyaml/engine/internal/system.native.kt, src/nativeMain/kotlin/org/snakeyaml/engine/v2/api/lowlevel/Compose.kt, src/nativeMain/kotlin/org/snakeyaml/engine/v2/api/lowlevel/Parse.kt, src/nativeMain/kotlin/org/snakeyaml/engine/v2/representer/platformRepresenter.native.kt, src/nativeMain/kotlin/org/snakeyaml/engine/v2/schema/JsonSchema.kt
* tidied up the K/N convention plugin
* removed some of the more esoteric targets (which can always be re-enabled)
* added more runners to the workflow
=> Enable Kotlin Native

src/commonMain/kotlin/org/snakeyaml/engine/v2/constructor/StandardConstructor.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/nodes/MappingNode.kt, src/commonMain/kotlin/org/snakeyaml/engine/v2/nodes/Node.kt
Updating `MappingNode` to be immutable makes the code more Kotlin-esque
Change split off from #59
=> Update `MappingNode.value` to be immutable

src/jvmTest/java/org/snakeyaml/engine/issues/issue25/DumpToStringTest.java, src/jvmTest/java/org/snakeyaml/engine/usecases/recursive/RecursiveMapTest.java, src/jvmTest/java/org/snakeyaml/engine/usecases/references/ReferencesTest.java, src/jvmTest/java/org/snakeyaml/engine/usecases/tags/TimestampTagTest.java
Cherry picks a couple of updates from snakeyaml-engine
* https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/075b7924812a115080ba707bffe4c5541343dd95
* https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/2d85f669dd347053d29c9ec67e6c22bb3f1708f3
There have been other commits in snakeyaml-engine but these are unrelated to the code base. With these two commits we should be fully up to date.
=> Cherry pick updates from SnakeYAML

.github/workflows/build.main.kts
Thanks to this, it will be easier to handle version updates, which should be mostly automatic now.
=> Switch to bindings server

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/YamlUnicodeReader.kt
- Refactorings, to improve readability.
- Avoid reading the entire input eagerly (eager reading interferes with InputStreams, e.g. `System.in`).
=> Refactor YamlUnicodeReader

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/nodes/Tag.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/representer/CommonRepresenter.kt
=> Remove deprecated Tag constructor

snake-kmp-benchmarks/build.gradle.kts
=> tidy benchmarks build script

.github/workflows/benchmark.main.kts, .github/workflows/benchmark.yaml, .github/workflows/build.main.kts, .github/workflows/build.yaml, .github/workflows/release.main.kts, .github/workflows/release.yaml
See https://github.com/krzema12/snakeyaml-engine-kmp/pull/255#discussion_r1817840117
Apparently Temurin is one of the most recommended ones.
=> Switch JDK distribution to Temurin

MAINTENANCE.md
See it rendered here: https://github.com/krzema12/snakeyaml-engine-kmp/blob/document-release-process/MAINTENANCE.md
=> Document the release process

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/api/LoadSettingsBuilder.kt, upstream-commit.txt
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/e274d600fb1da0b6215b65801a0eea0d303e6a4d.
=> [Port from snakeyaml-engine] Update setEnvConfig Javadoc in LoadSettingsBuilder

README.md
So that it's clear what this number means.
=> docs: describe the badge in README

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/parser/ParserImpl.kt
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/289
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/248edde3c2d5bd480d9b75218e0298527c32897c
=> [Port from snakeyaml-engine] Improve Javadoc for comments in the directives

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/emitter/Emitter.kt
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/282
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/18c7574fb1588a640dc374ed822febbdcd611f88
=> [Port from snakeyaml-engine] Refactor: improve Emitter as in SnakeYAML

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/serializer/NumberAnchorGenerator.kt, src/jvmTest/java/it/krzeminski/snakeyaml/engine/kmp/comments/EmitterWithCommentEnabledTest.kt
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/286
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/4ed7a0affa7fd0626ddf2a2b4c66f09b5ea5c52f
=> [Port from snakeyaml-engine] Try to keep the anchor name when available

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/ScannerImpl.kt
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/291
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/cb2e934a207723dc0f22b37fbfcc953c21a8b240
=> [Port from snakeyaml-engine] ScannerImpl scanFlow* append to existing StringBuilder

api/snakeyaml-engine-kmp.api, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/common/ScalarStyle.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/emitter/Emitter.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/events/ScalarEvent.kt, src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/representer/BaseRepresenter.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/usecases/json/DumperJsonTest.kt
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/5df68d14ee12742f882acc716de3cc04e90c4fe5
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/285
=> [Port from snakeyaml-engine] Dump as JSON

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/serializer/Serializer.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/issues/issue53/DumpWithoutCommentsTest.kt, src/jvmTest/java/org/snakeyaml/engine/v2/comments/SerializerWithCommentEnabledTest.java
Ports both changes at once since after porting just one, the project doesn't compile or the tests don't pass:
* https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/a6e00555a812b1a1a4b219f30c9b0882246f2d01
* https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/e998478fd24fa9374b938482f482396232f71ede
Closes https://github.com/krzema12/snakeyaml-engine-kmp/issues/288
=> [Port from snakeyaml-engine] Fix issue 53

src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/StringOutputStream.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/comments/EmitterWithCommentEnabledTest.kt
Part of https://github.com/krzema12/snakeyaml-engine-kmp/issues/269
=> Commonize EmitterWithCommentEnabledTest

karma.config.d/karma.conf.js
Part of https://github.com/krzema12/snakeyaml-engine-kmp/issues/307.
Helped get https://github.com/krzema12/snakeyaml-engine-kmp/pull/410 through.
=> Extend more Karma timeouts

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/parser/Parser.kt
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/b484094bfcea73d167a2d284ec8289e4ce3d316f
=> [Port from snakeyaml-engine] Clarify when to expect NoSuchElementException

src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/comments/DumpCommentInFlowStyleTest.kt
Fixes https://github.com/krzema12/snakeyaml-engine-kmp/issues/452.
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/d5aaefdd1cd3230cf63b545e5c0150b5269a56ac.
=> [Port from snakeyaml-engine] Improve DumpCommentInFlowStyleTest

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/emitter/Emitter.kt, src/commonTest/kotlin/it/krzeminski/snakeyaml/engine/kmp/comments/EmitterWithCommentEnabledTest.kt
Fixes https://github.com/krzema12/snakeyaml-engine-kmp/issues/508.
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/b6e388bd527df13d2fae4ce1956e6582248a6ac0.
=> [Port from snakeyaml-engine] Write commented empty strings in ExpectBlockSequenceItem

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/emitter/Emitter.kt
Fixes https://github.com/krzema12/snakeyaml-engine-kmp/issues/509.
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/921025100e96e60c9509f3b05b5697bd963e9311.
=> [Port from snakeyaml-engine] Improve analysis - use scalar style to check for quotes

src/commonMain/kotlin/it/krzeminski/snakeyaml/engine/kmp/scanner/StreamReader.kt
Fixes https://github.com/krzema12/snakeyaml-engine-kmp/issues/572.
Ports https://bitbucket.org/snakeyaml/snakeyaml-engine/commits/474abb4bbd8cbdc3de199b82690dcb30ebab9810.
=> [Port from snakeyaml-engine] Refactor StreamReader.update() method to make it simpler
